spring:
    datasource:
        url: jdbc:postgresql://printer_db:${POSTGRES_PORT:dummy}/${POSTGRES_DB:dummy}
        driver-class-name: org.postgresql.Driver
        username: ${POSTGRES_USER:dummy}
        password: ${POSTGRES_PASSWORD:dummy}
    jpa:
        database: postgresql
        show-sql: false
        hibernate:
            ddl-auto: update
        open-in-view: false

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"

server:
    port: 8080
