spring:
    datasource:
        url: jdbc:postgresql://localhost:5435/printer
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres
    jpa:
        database: postgresql
        show-sql: true
        hibernate:
            ddl-auto: update

server:
    port: 8090
