spring:
    datasource:
        url: jdbc:postgresql://localhost:5435/printer
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres
    jpa:
        database: postgresql
        show-sql: false
        hibernate:
            ddl-auto: update

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"

server:
    port: 8080
